import type { User, Station, Charger, Booking } from "./types"

export const mockUsers: User[] = [
  {
    id: "admin-1",
    email: "admin@evcharge.com",
    name: "Admin User",
    role: "admin",
    phone: "+55 11 99999-9999",
    created_at: new Date().toISOString(),
  },
  {
    id: "user-1",
    email: "joao@email.com",
    name: "João Silva",
    role: "user",
    phone: "+55 11 98888-8888",
    created_at: new Date().toISOString(),
  },
]

export const mockStations: Station[] = [
  {
    id: "station-1",
    name: "Shopping Ibirapuera",
    address: "Av. Ibirapuera, 3103 - São Paulo, SP",
    latitude: -23.5965,
    longitude: -46.6579,
    total_chargers: 8,
    available_chargers: 5,
    price_per_kwh: 0.89,
    power_output: "50 kW",
    connector_types: ["CCS2", "CHAdeMO", "Type 2"],
    amenities: ["Wi-Fi", "Café", "Banheiro", "Loja"],
    status: "active",
    owner_id: "admin-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "station-2",
    name: "Estação Paulista",
    address: "Av. Paulista, 1578 - São Paulo, SP",
    latitude: -23.5613,
    longitude: -46.6565,
    total_chargers: 6,
    available_chargers: 3,
    price_per_kwh: 0.95,
    power_output: "150 kW",
    connector_types: ["CCS2", "Type 2"],
    amenities: ["Wi-Fi", "Segurança 24h"],
    status: "active",
    owner_id: "admin-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "station-3",
    name: "Centro Empresarial",
    address: "Av. Faria Lima, 3477 - São Paulo, SP",
    latitude: -23.5754,
    longitude: -46.689,
    total_chargers: 12,
    available_chargers: 8,
    price_per_kwh: 0.85,
    power_output: "100 kW",
    connector_types: ["CCS2", "CHAdeMO", "Type 2", "Tesla"],
    amenities: ["Wi-Fi", "Café", "Banheiro", "Estacionamento Coberto"],
    status: "active",
    owner_id: "admin-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "station-4",
    name: "Terminal Rodoviário",
    address: "R. Mário de Andrade, 664 - São Paulo, SP",
    latitude: -23.535,
    longitude: -46.636,
    total_chargers: 4,
    available_chargers: 2,
    price_per_kwh: 0.92,
    power_output: "75 kW",
    connector_types: ["CCS2", "Type 2"],
    amenities: ["Wi-Fi", "Banheiro", "Lanchonete"],
    status: "active",
    owner_id: "admin-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockChargers: Charger[] = [
  {
    id: "charger-1",
    station_id: "station-1",
    charger_number: "01",
    status: "available",
    connector_type: "CCS2",
    power_output: "50 kW",
  },
  {
    id: "charger-2",
    station_id: "station-1",
    charger_number: "02",
    status: "occupied",
    connector_type: "CHAdeMO",
    power_output: "50 kW",
  },
  {
    id: "charger-3",
    station_id: "station-1",
    charger_number: "03",
    status: "available",
    connector_type: "Type 2",
    power_output: "50 kW",
  },
]

export const mockBookings: Booking[] = [
  {
    id: "booking-1",
    user_id: "user-1",
    station_id: "station-1",
    charger_id: "charger-2",
    start_time: new Date().toISOString(),
    end_time: new Date(Date.now() + 3600000).toISOString(),
    status: "active",
    total_kwh: 45.5,
    total_cost: 40.5,
    payment_status: "pending",
    created_at: new Date().toISOString(),
  },
]
